export interface FormElements extends HTMLCollection {
	code: HTMLInputElement
	layout: HTMLInputElement
	player: HTMLInputElement
	invertL: HTMLInputElement
	invertR: HTMLInputElement
	disJoyXAxis: HTMLInputElement
	disJoyYAxis: HTMLInputElement
	dblClickLoadSave: HTMLInputElement
	changeKeyOnDrag: HTMLInputElement
	vibrate: HTMLInputElement
	vibrateJoystick: HTMLInputElement
	vibrationFromGame: HTMLInputElement
	vgamepad: HTMLInputElement
	background: HTMLInputElement
	color: HTMLInputElement
	border: HTMLInputElement
	active: HTMLInputElement
	bgImage: HTMLInputElement
	bgOpacity: HTMLInputElement
	bgBlur: HTMLInputElement
	customCSS: HTMLInputElement
	customJS: HTMLInputElement
	pluginMobile: HTMLInputElement
	driveSensitivity: HTMLInputElement
	drivePrecision: HTMLInputElement
	debug: HTMLInputElement
	lock: RadioNodeList
	hide: RadioNodeList
}
