on:
  push:
    tags:
      - 'v*'

name: Build Executable

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          architecture: x64

      - name: Bypass VGamepad setup.py
        run: reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Nefarius Virtual Gamepad Emulation Bus Driver" /v DisplayName /t REG_SZ /d "Nefarius Virtual Gamepad Emulation Bus Driver" /f

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: .\build.bat

      - name: Rename executable
        run: mv "bin/MobyStk.exe" "bin/MobyStk-${{github.ref_name}}-Windows-x64.exe"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: bin/MobyStk-${{github.ref_name}}-Windows-x64.exe

  build-linux:
    name: Build Linux Executable
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          architecture: x64

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            chmod +x build.sh
            ./build.sh

      - name: Rename executable
        run: mv "bin/MobyStk" "bin/MobyStk-${{github.ref_name}}-Linux-x64"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: bin/MobyStk-${{github.ref_name}}-Linux-x64

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    steps:
      - name: Download Artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: Download Artifacts (Linux)
        uses: actions/download-artifact@v4
        with:
          name: linux-build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ''
          files: |
            ./MobyStk-${{github.ref_name}}-Windows-x64.exe
            ./MobyStk-${{github.ref_name}}-Linux-x64
          fail_on_unmatched_files: true
          prerelease: ${{endsWith(github.ref_name, '-beta')}}
